version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - echo build over
artifacts:
  files:
    - target/spring-docker.jar
  discard-paths: yes